name: Prevent Merging from multiple branches

on:
  pull_request:
    branches:
      - main

jobs:
  prevent-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        if: ${{ github.head_ref == 'custom-lint-script' || github.head_ref == 'custom-install-lint-script' }}
        run: exit 1
